services:
  db:
    image: mysql:8.0.30
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
    networks:
      - wordpress_default
  wordpress:
    image: wordpress:6.0.1-php8.1-apache
    volumes:
      - ./wordpress:/var/www/html/
      - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini
    ports:
      - 80:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - wordpress_default

networks:
  wordpress_default:
volumes:
  db_data:
